=== VijayEluri/qualm/qualm.dtd
<!ELEMENT qualm-data (title?,midi-channels, patches, cue-stream+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT midi-channels (channel+)>
<!ELEMENT channel (#PCDATA)>
<!ATTLIST channel
	  device-type CDATA #IMPLIED
	  num (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED>
<!--
     <midi-channels>
       <channel num="1">Main Keyboard</channel>
       <channel num="2" 
		device-type="Roland JV-1080">Auxiliary Keyboard</channel>
       <channel num="10">Drum Kit</channel>
     </midi-channels>
-->
<!ELEMENT patches (patch,(patch|patch-alias)*)>
<!ELEMENT patch (#PCDATA)>
<!ATTLIST patch
	  num CDATA #REQUIRED
	  bank CDATA #IMPLIED
	  remark CDATA ""
	  id ID #REQUIRED>
<!ELEMENT patch-alias (#PCDATA)>
<!ATTLIST patch-alias
	  target IDREF #REQUIRED
	  id ID #REQUIRED>
<!--
     <patches>
       <patch num="1" id="p1">Nice Piano</patch>
       <patch-alias id="p1_lookalike" target="p1">V. Nice Piano</patch-alias>
       <patch num="2" id="p2">TremStr/Str</patch>
       <patch num="5" id="p5" remark="GruvyOrgn">Organ</patch>
     </patches>
-->

<!ELEMENT map-events (map-from,map-to)>
<!ELEMENT map-from (note-on|note-off|control-change|program-change)>
<!ELEMENT map-to (note-on|note-off|control-change|program-change)>

<!-- 
     <map-events>
       <map-from><control-change channel="1" control="soft"/></map-from>
       <map-to><control-change channel="2" control="soft"/></map-to>
     </map-events>
-->

<!ELEMENT events (note-on|note-off|control-change|program-change|advance)+>

<!ELEMENT cue-stream (global?,cue*)>
<!ATTLIST cue-stream id ID #IMPLIED>
<!ELEMENT global (trigger|map-events)*>

<!ELEMENT cue (trigger|events|map-events)*>
<!ATTLIST cue song CDATA #REQUIRED measure CDATA #REQUIRED>
<!ELEMENT trigger (note-on|note-off|control-change|program-change|clear)>
<!ATTLIST trigger
	  delay CDATA #IMPLIED
	  override IDREF #IMPLIED
	  reverse (yes) #IMPLIED
	  id ID #IMPLIED>
<!ELEMENT note-on EMPTY>
<!ATTLIST note-on 
	  channel (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED
	  note CDATA #REQUIRED>
<!ELEMENT note-off EMPTY>
<!ATTLIST note-off 
	  channel (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED 
	  note CDATA #REQUIRED>
<!ELEMENT control-change EMPTY>
<!ATTLIST control-change
	  channel (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED
	  control CDATA #REQUIRED
	  threshold CDATA #IMPLIED>
<!ELEMENT clear EMPTY>
<!ATTLIST clear 
	  channel (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED 
	  duration CDATA #REQUIRED>

<!ELEMENT program-change EMPTY>
<!ATTLIST program-change
	  channel (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16) #REQUIRED 
	  patch IDREF #REQUIRED>

<!ELEMENT advance EMPTY>
<!ATTLIST advance 
          stream IDREF #REQUIRED
          song CDATA #IMPLIED
          measure CDATA #IMPLIED>

=== VijayEluri/qualm/src/qualm/testing/junit/qdl-1.xml
<?xml version="1.0"?>
<!DOCTYPE qualm-data PUBLIC "-//QUALM/DTD Qualm Data//EN" "http://qualm.berlios.de/qualm.dtd">

<qualm-data>
  <title>QDL-1</title>
  <midi-channels>
    <channel num="1">Lower Kbd</channel>
    <channel num="2">Upper Kbd</channel>
    <channel num="10">Drums</channel>
  </midi-channels>
  <patches>
    <patch id="P1" bank="User" num="1">Patch 1</patch>
    <patch id="P2" bank="PrA" num="2" volume="20">Patch 2</patch>
    <patch id="P3" bank="XpA" num="3" volume="80%">Patch 3</patch>
    <patch id="Timpani" bank="PrA" num="5"/>
    <patch-alias id="P3_2" target="P3" volume="100%">Patch 3 Alias</patch-alias>
  </patches>

  <cue-stream id="First_Stream">
    <global>
      <trigger><note-on channel="1" note="c6"/></trigger>
      <trigger reverse="yes"><note-on channel="1" note="c2"/></trigger>
      <map-events>
	<map-from><control-change channel="1" control="damper"/></map-from>
	<map-to><control-change channel="2" control="80"/></map-to>
      </map-events>
    </global>
    <cue song="3" measure="1">
      <events><program-change channel="1" patch="P1"/></events>
      <trigger delay="2.5"><note-on channel="2" note="g2"/></trigger>
    </cue>
    <cue song="3" measure="16">
      <events>
	<program-change channel="10" patch="Timpani"/>
	<program-change channel="1" patch="P3"/>
      </events>
    </cue>
  </cue-stream>
  <cue-stream id="Second_Stream">
    <global>
      <trigger><note-on channel="2" note="c6"/></trigger>
    </global>
    <cue song="1" measure="1">
      <events><program-change channel="2" patch="P2"/></events>
    </cue>
    <cue song="2" measure="10">
      <events>
	<program-change channel="2" patch="P3_2"/>
	<advance stream="First_Stream"/>
      </events>
    </cue>
  </cue-stream>
</qualm-data>

=== VijayEluri/qualm/test-input.xml
<?xml version="1.0" standalone='yes'?>
<!DOCTYPE qualm-data PUBLIC "-//QUALM/DTD Qualm Data//EN" "qualm.dtd">
<qualm-data>
  <title>Bat Boy Keyboard II</title>
  <midi-channels>
    <channel num="1">Lower Keyboard</channel>
    <channel num="2">Upper Keyboard</channel>
    <channel num="4">Drum Kit</channel>
  </midi-channels>
  <patches>
    <patch id="P1" bank="User" num="1">Nice Piano</patch>
    <patch id="P2" bank="User" num="2">TremStr/Str</patch>
    <patch id="P3" bank="User" num="3">Strs/FzzClav</patch>      
    <patch id="P4" bank="PrA"  num="15">Rhodes</patch>       
    <patch id="P5" bank="User" num="5">Organ</patch>
    <patch id="P95" bank="User" num="95">LKB/TmpF</patch>
    <patch id="P96" bank="User" num="96">TmpG/TmpD</patch>
  </patches>
  <global>
    <trigger><note-on channel="3" note="0"/></trigger>
    <trigger><note-on channel="1" note="c8"/></trigger>
    <trigger reverse="yes"><note-on channel="1" note="a0"/></trigger>
    <map-events>
      <map-from><control-change channel="1" control="soft"/></map-from>
      <map-to><control-change channel="2" control="soft"/></map-to>
    </map-events>
  </global>
  <start-events>
    <program-change channel="1" patch="P2"/>
    <program-change channel="2" patch="P5"/>
    <program-change channel="4" patch="P95"/>
  </start-events>
 
  <cue song="1a" measure="10">
    <events><program-change channel="1" patch="P3"/></events>
  </cue>
  <cue song="2" measure="35">
    <events><program-change channel="1" patch="P1"/></events>
  </cue>
  <cue song="2" measure="102">
    <events><program-change channel="1" patch="P4"/></events>
  </cue>
  <cue song="3" measure="1">
    <events>
      <program-change channel="4" patch="P96"/>
      <program-change channel="1" patch="P5"/>
    </events>
  </cue>
  <cue song="3" measure="16">
    <trigger><note-on channel="2" note="g2"/></trigger>
    <events><program-change channel="2" patch="P3"/></events>
  </cue>

</qualm-data>
